global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Media;
global using Application = System.Windows.Application;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using Button = System.Windows.Controls.Button;
global using Color = System.Windows.Media.Color;
global using ColorConverter = System.Windows.Media.ColorConverter;
global using Control = System.Windows.Controls.Control;
global using FlowDirectionMode = System.Windows.FlowDirection;
global using Pen = System.Windows.Media.Pen;
global using Point = System.Windows.Point;
global using ScaleTransform = System.Windows.Media.ScaleTransform;
global using ThemeMode = Vaktr.Core.Models.ThemeMode;
global using TranslateTransform = System.Windows.Media.TranslateTransform;
global using UserControl = System.Windows.Controls.UserControl;
